In [1]:
import numpy as np

# 1. Creating 1D, 2D and 3D Arrays

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\n3D Array:")
print(arr3)


# 2. Dimensions, Shape and Data Type

print("\nDimensions:")
print("arr1:", arr1.ndim)
print("arr2:", arr2.ndim)
print("arr3:", arr3.ndim)

print("\nShape:")
print("arr1:", arr1.shape)
print("arr2:", arr2.shape)
print("arr3:", arr3.shape)

print("\nData Type:")
print(arr1.dtype)


# 3. Indexing

print("\nIndexing:")
print("First element:", arr1[0])
print("Last element:", arr1[-1])
print("2D element:", arr2[1, 2])
print("3D element:", arr3[1, 0, 1])


# 4. Slicing

print("\nSlicing:")
print("arr1[1:4]:", arr1[1:4])
print("Every second element:", arr1[::2])
print("First row of arr2:", arr2[0, :])
print("Second column of arr2:", arr2[:, 1])


# 5. Reshaping

numbers = np.arange(1, 13)

print("\nOriginal Array:")
print(numbers)

reshaped = numbers.reshape(3, 4)

print("\nReshaped Array:")
print(reshaped)


# 6. Generating Arrays

print("\nZeros:")
print(np.zeros((2, 3)))

print("\nOnes:")
print(np.ones((2, 3)))

print("\nArange:")
print(np.arange(0, 10, 2))

print("\nLinspace:")
print(np.linspace(0, 1, 5))


# 7. Mathematical Operations

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("\nMathematical Operations:")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square:", a ** 2)
print("Square Root:", np.sqrt(a))


# 8. Vectorized Operations

values = np.array([1, 2, 3, 4, 5])

print("\nVectorized Operation:")
print(values * 10 + 5)


# 9. Boolean Masking

data = np.array([12, 5, 18, 7, 25, 10])

print("\nBoolean Masking:")
print("Values greater than 10:", data[data > 10])
print("Values less than or equal to 10:", data[data <= 10])


# 10. Broadcasting

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

values = np.array([1, 2, 3])

print("\nBroadcasting:")
print(matrix + values)


# 11. Aggregate Functions

scores = np.array([65, 80, 75, 90, 85])

print("\nAggregate Functions:")
print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))


# 12. Numerical Data Analysis Example

marks = np.array([
    [78, 85, 90],
    [65, 70, 75],
    [88, 92, 95],
    [55, 60, 68]
])

print("\nStudent Marks:")
print(marks)

average = np.mean(marks, axis=1)

print("\nAverage of each student:")
print(average)

print("\nStudents with average >= 75:")
print(average[average >= 75])

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Dimensions:
arr1: 1
arr2: 2
arr3: 3

Shape:
arr1: (5,)
arr2: (2, 3)
arr3: (2, 2, 2)

Data Type:
int64

Indexing:
First element: 10
Last element: 50
2D element: 6
3D element: 6

Slicing:
arr1[1:4]: [20 30 40]
Every second element: [10 30 50]
First row of arr2: [1 2 3]
Second column of arr2: [2 5]

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Arange:
[0 2 4 6 8]

Linspace:
[0.   0.25 0.5  0.75 1.  ]

Mathematical Operations:
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Square: [ 100  400  900 1600]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532]

Vectorized Operation:
[15 25 35 45 55]

Boolean Masking:
Values greater than 10: [12 18 25]
Values less than or equal to 10: [ 